engines:
  eslint:
    enabled: true
    checks:
      max_line_length:
        enabled: false

languages:
  JavaScript: true

exclude_paths:
- bower_components/
- config/
- public/
- script/
- tests/
- tmp/
