engines:
  watson:
    enabled: false
    checks:
      transformEmberDataModelLookups:
        enabled: false
      transformEmberDataAsyncFalseRelationships:
        enabled: false
      transformPrototypeExtensions:
        enabled: false
      transformQUnitTest:
        enabled: false
languages:
   JavaScript: true

exclude_paths:
- bower_components/
- config/
- public/
- script/
- tests/
- tmp/
