---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- "tests/"
- "public/"
- "cordova/"
- "scripts/"
- "tmp/"
- "app/routes/"
- "app/styles/"
- "app/locales/"
- "config/"



